common/models/Booking.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;
use common\components\RegisterFromBehavior;
use yii2tech\ar\softdelete\SoftDeleteBehavior;
use Carbon\Carbon;
use yii\helpers\Html;
use common\components\Util;
use yii\db\ActiveRecord;
use yii\behaviors\AttributeBehavior;

/**
 * This is the model class for table "booking".
 *
 * @property integer $id
 * @property string $booking_code
 * @property integer $customer_id
 * @property integer $store_id
 * @property string $booking_date
 * @property string $memo
 * @property string $memo_manager
 * @property integer $staff_id
 * @property string $start_time
 * @property string $end_time
 * @property string $status
 * @property string $action
 * @property string $demand
 * @property integer $number_of_people
 * @property string $booking_price
 * @property string $booking_discount
 * @property string $booking_total
 * @property string $to_home_delivery_flg
 * @property string $customer_specify
 * @property string $del_flg
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 * @property integer $point_use 
 */
class Booking extends \yii\db\ActiveRecord
{
    const BOOKING_STATUS_PENDING  = "01" ;
    const BOOKING_STATUS_APPROVE  = "02" ;
    const BOOKING_STATUS_FINISH   = "03" ;
    const BOOKING_STATUS_CANCEL   = "04" ;
    const BOOKING_STATUS_DENY     = "05" ;
    const BOOKING_STATUS_CANCEL_BY_CUSTOMER     = "06" ;
    const BOOKING_ABOVE     = 1 ;
    const BOOKING_BELOW     = 2 ;
    const BOOKING_EQUAL     = 3 ;

    public $full_name;
    public $phone_contact;
    public $product_name;
    public $booking_date_from;
    public $booking_date_to;
    public $productSelect;
    public $staffSelect;
    public $couponSelect;
    public $store_name, $first_name, $last_name, $booking_resources;
    public $name;
    public $booking_id;
    public $store;
    public $product;
    public $option;
    public $start_date;
    public $end_date;
    public $booking_type;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'booking';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [[ 'customer_id', 'store_id'], 'required'],
         
            [['customer_id', 'store_id', 'staff_id', 'number_of_people', 'created_at', 'created_by', 'updated_at', 'updated_by'], 'integer'],
            [['booking_date','booking_method','to_home_delivery_flg','booking_code','memo','couponSelect','productSelect','staffSelect','customer_specify'], 'safe'],
           [['booking_price', 'booking_discount', 'booking_total' ,'point_use'], 'number','numberPattern' => '/^[0-9]+(,[0-9]+)*$/'],
            [['point_use'], 'number', 'max' => 9999999.999, 'min' => 0,'numberPattern' => '/^[0-9]+(,[0-9]+)*$/'],
            [['point_use'], 'string', 'max' => 9],
            [['booking_code'], 'string', 'max' => 20],
            [['memo', 'memo_manager'], 'string', 'max' => 500],
            [['start_time', 'end_time'], 'string', 'max' => 5],
            [['status', 'action'], 'string', 'max' => 2],
            [['demand'], 'string', 'max' => 240],
            [['to_home_delivery_flg', 'del_flg'], 'string', 'max' => 1],
            [['phone_contact'], 'checkPhoneExit'],
            [['point_use'],'checkPoindValid','except'=> 'statusBooking'],
            [[ 'productSelect'], 'required','on'=>['bookingAdmin','bookingSeatAdmin'] ,'message'=>'商品またはクーポンを選択してください。'],
            [[ 'staffSelect'], 'required','on'=>'bookingAdmin' ,'message'=> '日時・スタッフを選択してください。'],
            [[ 'staffSelect'], 'required','on'=>'bookingSeatAdmin' ,'message'=> '日時・席タイプを選択してください。'],
        ];
    }
    public function behaviors() {
      return [
        TimestampBehavior::className(),
        BlameableBehavior::className(),
        RegisterFromBehavior::className(),  
        'softDeleteBehavior' => [
          'class' => SoftDeleteBehavior::className(),
          'softDeleteAttributeValues' => [
            'del_flg' => true
          ],
        ]
      ];
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'booking_code' => Yii::t('backend', 'Booking Code') ,
            'customer_id' => 'Customer ID',
            
            'booking_date' => 'Booking Date',
            'memo' => 'Memo',
            'memo_manager' => 'Memo Manager',
            'staff_id' => 'Staff ID',
            'seat_id' => 'Seat ID',
            'start_time' => 'Start Time',
            'end_time' => 'End Time',
            'status' => 'Status',
            'action' => 'Action',
            'demand' => 'Demand',
            'number_of_people' => 'Number Of People',
            'booking_price' => 'Booking Price',
            'booking_discount' => 'Booking Discount',
            'booking_total' => 'Booking Total',

            'del_flg' => 'Del Flg',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
            'booking_method' => Yii::t('backend', 'Booking Method'),
            'to_home_delivery_flg' => Yii::t('backend', 'Home delivery'),
            'booking_date_from' => Yii::t('backend', 'Booking Date'),
            'booking_date_to' => Yii::t('backend', 'Booking Date'),
            'store_id' => Yii::t('backend', 'Select a store'),
            'customer_jan_code' => Yii::t('backend', 'Code Membership'),
            'customer_name' => Yii::t('backend', 'Name Customer'),
            'rank' => Yii::t('backend', 'Rank Customer'),
            'number_visit_min' => Yii::t('backend', 'Visit number'),
            'number_visit_max' => Yii::t('backend', 'Visit number'),
            'birth_date_from' => Yii::t("backend", "Birthday"),
            'birth_date_to' => Yii::t("backend", "Birthday"),
            'history_date_from' => Yii::t('backend', 'Process Date'),
            'history_date_to' => Yii::t('backend', 'Process Date'),
            'product_name' => Yii::t('backend', 'Name Product Booking'),
            'list_catogory' => Yii::t('backend', 'Category'),
            'last_visit_date_from' => Yii::t('backend', 'Last visit time'),
            'last_visit_date_to' => Yii::t('backend', 'Last visit time'),
            'last_staff_id' => Yii::t('backend', 'Last time staff'),
            'list_category' => Yii::t('backend', 'Product Category'),
            'customer_first_name' => Yii::t('backend', 'First name'),
            'customer_last_name' => Yii::t('backend', 'Last name'),
            'mobile' => Yii::t('backend', 'Phone'),
            'booking_time_min' => Yii::t('backend', 'Booking Times'),
            'booking_time_max' => Yii::t('backend', 'Booking Times'),
            'last_seat_id' => Yii::t('backend', 'Last Seat'),
            'service_staff_id' => Yii::t('backend', 'Service staff'),
            'seat_type' => Yii::t('backend', 'Type Seat Name'),
            'status' => Yii::t('backend', 'Booking status'),
            'point_use' => Yii::t('backend', 'Point use'),
            'demand' => Yii::t('backend', 'Demand'),
            'memo_manager' => Yii::t('backend', 'Memo manager'),
            'sex' => Yii::t('backend','Sex'),
            'productSelect' => '商品またはクーポンを選択してくだいさい。',
            'staffSelect' => '日時・スタッフをを選択してくだいさい。',
            'customer_specify' => \Yii::t('backend','Customer specified')
        ];
    }
    /**
     * @inheritdoc
     * @return MstBookingQuery the active query used by this AR class.
     */
//    public static function find()
//    {
//        return new MstBookingQuery(get_called_class());
//    }
    public static function find($noDel = true)
    {
        if($noDel){
            
            return parent::find()->where((new \common\components\FindPermission)->getPermissionCondition(Booking::tableName(), true));
        }
        return parent::find();
    }
//    public function beforeSave($insert)
//    {
//        if (parent::beforeSave($insert)) {
//            // Place your custom code here
//          $this->booking_date = strtotime($this->booking_date);
//
//            return true;
//        } else {
//            return false;
//        }
//    }

    public function getmasterStore() {
        return $this->hasMany(MasterStore::className(), ['id' => 'store_id']);
    }
    public function getImageBlackList()
    {
        $model = CustomerStore::find()->andWhere(['customer_id'=> $this->customer_id , 'store_id' => $this->store_id])->one();
        if(count($model) == 1 && $model->black_list_flg == "1"){
          return '<i class="fa fa-exclamation-triangle fa-2x"  style="color:red" aria-hidden="true"></i>';
        }else{
          return '';
        }

    }
    public function getTempStatus()
    {
        $model = CustomerStore::find()->andWhere(['customer_id'=> $this->customer_id , 'store_id' => $this->store_id])->one();
        if($this->status== Booking::BOOKING_STATUS_PENDING){
          return '<span class="temp-status"> 仮 </span>';
        }else{
          return '';
        }

    }
    public function getMasterCustomer()
    {
        return $this->hasOne(MasterCustomer::className(), ['id' => 'customer_id']);
    }
    
    public function getCustomerStore()
    {
        return $this->hasOne(CustomerStore::className(), ['customer_id' => 'customer_id'], ['store_id' => 'store_id']);
    }
    
    public function getOrder()
    {
        return $this->hasOne(MstOrder::className(), ['booking_id' => 'id']);
    }

    public function getStaff()
    {

backend/views/booking/_booking.php
<?php

  use yii\helpers\Html;
  use yii\grid\GridView;
  use yii\jui\DatePicker;
  use yii\widgets\Pjax;

/* @var $this yii\web\View */
  /* @var $searchModel common\models\BookingSearch */
  /* @var $dataProvider yii\data\ActiveDataProvider */
  \backend\assets\BookingAsset::register($this);
  $this->title = Yii::t('backend', 'Master Bookings');
  $this->params['breadcrumbs'][] = $this->title;
?>

<style>

  .obj-booking{
    /*background-color: #e3a1a1 !important;*/
    padding: 20px !important;
    border-radius: 15px; 

    background: #ff5ca6 !important;

  }
  .obj-booking-disable{
    /*background-color: #e3a1a1 !important;*/
    padding: 20px !important;
    border-radius: 15px; 

    background: #e3e3e3 !important;

  }
  /*  #schedule-table{
  
      width: 750px;
      height: 500px;
      overflow: hidden;
  
    }*/
  .scroll-container{
    height: 800px;
    overflow: hidden;
  }
  .ui-datepicker{
    z-index : 999 !important;
  }
</style>
<?php Pjax::begin(); ?>
<div class="row">
  <div class="col-lg-12 col-md-12">
    <div class="box box-info box-solid">
      <div class="box-header with-border">
        <h4 class="text-title"><b><?= $this->title ?></b></h4>
      </div>
      <div class="box-body content">
        <div class="col-md-12">
          <div class="common-box">
            <div class="box-header with-border common-box-h4 col-md-6">
              <h4 class="text-title"><b><?= Yii::t('backend', 'Booking') ?></b></h4>
            </div>
            <div class="box-body content">
              <div class="col-md-12">
                    
                <?= Html::beginForm(['booking/schedule'], 'post', ['data-pjax' => '', 'class' => 'form-inline' ,'id' => "booking-schedule" ] ); ?>
                 
               
                <h3 ><?= $date ?></h3>
                
                <?=
                  DatePicker::widget([
                    'id' => 'dateBooking',
                    'name' => 'dateBooking',
                    'value'  => $date,
                    'language' => 'ja',
                    'dateFormat' => 'yyyy-MM-dd',
                    "clientOptions" => [
                      "changeMonth" => true,
                      "changeYear" => true,
                      "defaultDate"=>$date ,
                    ]
                  ])
                  
                ?>
                <?= Html::submitButton(Yii::t('backend', 'Select a date'), ['class' => 'btn btn-lg btn-primary', 'name' => 'hash-button']) ?>
                 <?= Html::endForm() ?>
                
                <div class="scroll-container">
                  <div id="schedule-table" ></div>
                </div>  
                
                
                
               
              </div>
            </div>
          </div>


        </div>
      </div>
    </div>
  </div>
</div>

<script>
$(document).on('ready pjax:success', function() {
  
  var data = <?= $data ?>;
  var mergeData = <?= $mergeData ?>;
  console.log(data);
  console.log(mergeData);
//  var window.gon.mergeData = $("#mergeData").val();
        console.log(window.gon.data);
//    var mergeData = [{row: 1, col: 1, rowspan: 3, colspan: 1}];
// console.log( window.gon.mergeData);
    var selection;
    var cellRenderer = function (instance, td, row, col, prop, value, cellProperties) {

      Handsontable.renderers.TextRenderer.apply(this, arguments);

      td.innerHTML = '';

      if (typeof (value) === "string" && value != '' && value.indexOf('@') != -1) {

        var arrValue = value.split("@");
        var mergecell = arrValue[0];
        var id = arrValue[1];
        var content = arrValue[2];
        console.log(mergecell);
        td.setAttribute("rowSpan", mergecell);
        //        td.className = 'obj-booking';
        td.className = 'obj-booking-disable';
        td.innerHTML = content;
        td.setAttribute("id", id);

      }
      else {
        td.className = '';

        td.innerHTML = '';
      }


    };
    var megRenderer = function (instance, td, row, col, prop, value, cellProperties) {
      Handsontable.renderers.TextRenderer.apply(this, arguments);

      if (typeof (value) === "string" && value != '') {
        td.innerHTML = '';

        var content = "staff";

        td.className = 'obj-booking';

        td.innerHTML = content;


      }


    };

    var container = document.getElementById('schedule-table');
    var hot = new Handsontable(container, {
      data: data,
      //        width: 500,
      //        height: 500,
      colWidths: 100,
      rowHeights: 80,
      //       rowHeaders: true,
      //    colHeaders: true,
      fixedRowsTop: 1,
      fixedColumnsLeft: 1,
      contextMenu: true,
      mergeCells: mergeData,
      readOnly: true,
      fillHandle: {
        autoInsertRow: false,
      },
      className: "htMiddle",
      //      cells: function (row, col, prop) {
      //        var cellProperties = {};
      //        cellProperties.readOnly = true;
      //        if (col != 0 && row != 0) {
      //          this.renderer = cellRenderer;
      //        }
      //        return cellProperties;
      //      },

      afterSelection: function () {

        var temp = [];
        $.each(window.gon.mergeData, function (i, val) {

          temp.push(val['row'] + val['rowspan'] - 1 + ',' + val['col']);
          temp.push(val['row'] + ',' + val['col']);
        });
        
        tempSelect = this.getSelected()[2] + ',' + this.getSelected()[3];
        
        if ($.inArray(tempSelect, temp) != -1) {
          this.deselectCell();
        
        }


      },
      afterSelectionEnd: function () {

        selection = this.getSelected();
        //        console.log(selection);
        //        var cell = hot.getCellMeta(selection[0], selection[1]);

        var spanRow = ((selection[2] - selection[0]) + 1).toString();
        if (selection[0] != 0 && selection[1] != 0) {
          selectionCell = hot.setDataAtCell(selection[0], selection[1], spanRow);
          mergeData.push({row: selection[0], col: selection[1], rowspan: (selection[2] - selection[0]) + 1, colspan: 1});


          hot.updateSettings({
            mergeCells: mergeData,
            cells: function (row, col, prop) {
              var cellProperties = {};
              cellProperties.readOnly = true;
              if (row == selection[0] && col == selection[1]) {
                this.renderer = megRenderer;
              } else if (col != 0 && row != 0) {
                this.renderer = cellRenderer;
              }
              return cellProperties;
            }


          });

          mergeData.pop();
        }
      


        var id = $(".current").attr('id');
        if (typeof (id) === "string" && id != '') {
                    alert(id);
        }
        //           echo 'Cellclick();';



      },
    });
    hot.updateSettings({
      //        mergeCells: [
      //          {row: 5, col: 1, rowspan: 3, colspan: 1 }
      ////          {row: 2, col: 2, rowspan: 2, colspan: 1}
      //        ],
      cells: function (row, col, prop) {
        var cellProperties = {};
        cellProperties.readOnly = true;
        if (col != 0 && row != 0) {
          this.renderer = cellRenderer;
        }
        return cellProperties;
      }


    });
  })
</script>
 <?php Pjax::end(); ?>

backend/views/booking/_dialog_staff_setting.php
<?php

    use yii\helpers\Html;
    use yii\widgets\ActiveForm;
    use Carbon\Carbon;
    use common\models\StoreShift;
    use common\components\Constants;

/* @var $this yii\web\View */
    /* @var $model common\models\Booking */
    /* @var $form yii\widgets\ActiveForm */
?>
<style>
  .dialogContent {
    font-size: 22px;
  }
  .btn-sm{
    font-size: 12px; 
  }
  .row-padding{
    margin-top: 15px;
  }
</style>
<div class="master-booking-form">

  <?php $form = ActiveForm::begin([
                'action' => 'save-staff-work-day2', 
                'options' => [
                    'id' =>  'form-staff-setting-day',
                ], // important
                ]); ?>
  <div class="row"> 
    <div class="col-md-12">
      <div class="row">   
        <div class="col-md-2" >  
          <?= Html::radio('work_flg', $model['work_flg'] == 1 || $model['work_flg'] == null  ? true : false , ['value' => 1]); ?>
          <?= Html::label(Yii::t('backend', 'Working')); ?>
        </div> 
        <div class="col-md-10">
          <div class="shift-select">
            <?= Html::dropDownList('shift_id', $model['shift_id'], StoreShift::getAllShift($store_id), ['class' => 'form-control disabled','disabled'=>$model['work_flg'] == '1' || $model['work_flg'] == null ? false : true ]) ?>
          </div>
          <div class="work-off " id="work-off">
              <?php if(!empty($modelNotWorking)) {
                        foreach ($modelNotWorking as $item) { ?>
                            <div class="row row-padding">
                                <div class="col-md-3 ">
                                    <?= Html::dropDownList('start_work_off[]',$item['start_time'] , Constants::LIST_OPTION_SELECT_TIME, ['class' => 'form-control add-time-off']) ?>
                                </div>
                                <div class="col-md-1 ">
                                    ～
                                </div>
                                <div class="col-md-3">
                                    <?= Html::dropDownList('end_work_off[]', $item['end_time'], Constants::LIST_OPTION_SELECT_TIME, ['class' => 'form-control add-time-off']) ?>
                                </div>
                                <div class="col-md-4">
                                    <?= Html::textInput('reason_work_off[]', $item['reason'] , ['class' => 'form-control add-time-off', 'maxlength' => 20]) ?>
                                  
                                </div>
                                <i class="fa fa-times fa-2x btn-remove"  style="color:red;cursor: pointer;" aria-hidden="true"></i>
                            </div>
                       <?php }
                
              } ?>
          </div> 
          <br>
          <?= Html::button(Yii::t('backend', 'Add a schedule'), ['class' => 'btn common-button-submit' ,'id'=>'btn-add-schedule','disabled'=>$model['work_flg'] == '1' || $model['work_flg'] == null ? false : true]) ?>
        </div>
      </div> 
    </div>
    <div class="col-md-12">
      <div class="row">   
        <div class="col-md-2" >  
            
          <?= Html::radio('work_flg', $model['work_flg'] === '0'   ? true : false, ['value' => '0']); ?> 
          <?= Html::label(Yii::t('backend', 'Holiday')); ?>
        </div> 
        <div class="col-md-2">

        </div>
      </div> 
    </div>

       
    
    
  </div>
    <?= Html::hiddenInput('staff_id',$staffId) ?>
    <?= Html::hiddenInput('schedule_date',$schedule_date) ?>
    <?= Html::hiddenInput('store_id',$store_id) ?>
  <?php ActiveForm::end(); ?>
</div>

<div class="template-work-off hidden">
    <div class="row row-padding">
        <div class="col-md-3 ">
            <?= Html::dropDownList('start_work_off[]', null, Constants::LIST_OPTION_SELECT_TIME, ['class' => 'form-control']) ?>
        </div>
        <div class="col-md-1 ">
            ～
        </div>
        <div class="col-md-3">
            <?= Html::dropDownList('end_work_off[]', null, Constants::LIST_OPTION_SELECT_TIME, ['class' => 'form-control']) ?>
        </div>
        <div class="col-md-4">
            <?= Html::textInput('reason_work_off[]', null , ['class' => 'form-control', 'maxlength' => 20]) ?>
        </div>
      <i class="fa fa-times fa-2x btn-remove"  style="color:red;cursor: pointer;" aria-hidden="true"></i>
    </div>
</div> 


<script>
    $(document).ready(function () {
        $('#title-modal').text("<?= $title ?>");
        $(document).on('click', '[name="work_flg"]', function () {
          var self = $(this).val();
          if(self==0){
              $('.work-off').html('');
              $('[name="shift_id"]').attr('disabled',true);
              $('#btn-add-schedule').attr('disabled',true);
              
          }else{
              $('[name="shift_id"]').attr('disabled',false);
              $('#btn-add-schedule').attr('disabled',false);
          }
            
        })

    })
</script>  

backend/views/booking/_dialog_update.php
<?php

  use yii\helpers\Html;
  use yii\widgets\ActiveForm;
  use Carbon\Carbon;

/* @var $this yii\web\View */
  /* @var $model common\models\Booking */
  /* @var $form yii\widgets\ActiveForm */
?>
<style>
  .dialogContent {
    font-size: 22px;
  }
  .btn-sm{
     font-size: 12px; 
  }
</style>
<div class="master-booking-form">

  <?php $form = ActiveForm::begin(); ?>

  <?= Yii::t('backend', 'Customer name') ?> : <?= $model->customer_id ?> <br>

  <?= Yii::t('backend', 'Contact') ?> : <?= $model->customer_id ?> <br>

  <?= Yii::t('backend', 'Menu') ?> : <?= $model->menu_coupon_id ?> <br>

  <?= Yii::t('backend', 'Option') ?> : <?= $model->menu_coupon_id ?> <br>

  <?= Yii::t('backend', 'Coupon') ?> : <?= $model->coupon_id ?><br>

  <?= Yii::t('backend', 'Date time booking') ?> : <?= $model->start_time . " ～ " . $model->end_time ?>
  
  <br>

  <?= Yii::t('backend', 'Booking status') ?> : <?= $model->status ?>
  <?= Html::a(Yii::t('backend', 'Approval'), "", ['class' => 'btn btn-sm common-button-submit ']) ?>
  <?= Html::a(Yii::t('backend', 'Denial'), "", ['class' => 'btn btn-sm common-button-submit ']) ?>
  <?= Html::a(Yii::t('backend', 'Cancel'), "", ['class' => 'btn btn-sm common-button-submit ']) ?>
  <br>

  <?= Yii::t('backend', 'Responsible') ?> : <?= $model->staff->staff_name_kana ?><br>

  <?= Yii::t('backend', 'Seat') ?> : <?= $model->seat_id ?><br>

  <?= Yii::t('backend', 'Demand') ?> : <?= $model->demand ?><br>

  <?= Yii::t('backend', 'Memo') ?> : <?= $model->memo ?><br>
  
  <?= Yii::t('backend', 'Create at') ?> : <?= \Yii::$app->formatter->asDate($model->created_at, 'php:Y-m-d');  ?><br>

  <?= Yii::t('backend', 'Update at') ?> : <?= \Yii::$app->formatter->asDate($model->updated_at, 'php:Y-m-d');   ?><br>


  <?php ActiveForm::end(); ?>

</div>

backend/views/booking/_view_simple.php
<?php

    use yii\helpers\Html;
    use yii\bootstrap\ActiveForm;
    use yii\widgets\Pjax;
    use common\components\Constants;
    use common\models\Booking;
    use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
    /* @var $model common\models\Booking */
?>
<style>
  .master-booking-view{
    font-size: 17px;
  }
  .master-booking-view .row{
    margin-bottom: 10px;
  }
  .master-booking-view .btn-action{
    padding: 6px 10px;
    font-size: 16px;
  }
  .info-box{
    padding: 15px;
    background-color: #F9F9F9;
    padding-bottom: 2px;
  }
  .btn-view {
    background:none!important;
    border:none; 
    padding:0!important;
    font: inherit;
    /*border is optional*/
    border-bottom:1px solid blue; 
    cursor: pointer;
    color: blue;
  }
  .htMiddle.htDimmed {
    font-weight: bold;
  }
  .modal{
    background: none;
  }
</style>
<div class="master-booking-view">

  <div class="row">

    <div class="col-md-6">
      <b>
      <?= $model->masterCustomer->first_name . $model->masterCustomer->last_name . ' ' . Yii::t('backend', 'Sir') ?>
      </b>
    </div>

    <div class="col-md-4" style="font-size: 20px; color: blue">

        (
    <?= Html::a($model->booking_code, yii\helpers\Url::to([ '/booking/view'  , 'id' => $model->id]) , ['class'=>'btn-view']); ?>
        )
    </div>
    <div class="col-md-2">
        <?= $model->imageBlackList; ?>
    </div>
    
  </div>
  <hr>
   <?php if(isset($model->point_use ) && $model->point_use >0){ ?>
  <div class="row text-orange">
    <div class="col-md-3 text-orange" >
      <b><?= Yii::t('backend', 'Point use') ?></b>
    </div>
    <div class="col-md-9">
      <?= isset($model->point_use )?yii::$app->formatter->asInteger($model->point_use) :0?> P
    </div>
  </div>
   <?php } ?>
  
  <?php if(count($couponName) >0){ ?>
  <div class="row">
    <div class="col-md-3">
      <b><?= Yii::t('backend', 'Coupon') ?></b>
    </div>
    <div class="col-md-9">
        <?= implode(',', ArrayHelper::getColumn($couponName, 'name')) ?>
    </div>
  </div>
  <?php } ?>
  
  <?php if(count($productName) >0){ ?>
  <div class="row">
    <div class="col-md-3">
      <b><?= Yii::t('backend', 'Product') ?></b>
    </div>
    <div class="col-md-9">
        <?= implode('<br>', ArrayHelper::getColumn($productName, 'name')) ?>
    </div>
  </div>
  <?php } ?>
  
  <?php if(count($optionName) >0){ ?>
  <div class="row">
    <div class="col-md-3">
      <b><?= Yii::t('backend', 'Option') ?></b>
    </div>
    <div class="col-md-9">
      <?php
          $name = '';
          
            foreach ($optionName as $item) {
              $name .= $item->option->name . " : " . $item->product->name . ' <br>';
            }
          
          echo trim($name, ',');
      ?>
    </div>
  </div>
  <?php } ?>
  
  
  <div class="row">
    <div class="col-md-3">
      <b><?= Yii::t('backend', 'Booking status') ?></b>
    </div>
    <div class="col-md-9">
      <?= Constants::LIST_BOOKING_STATUS_KANRI[$model->status] ?>

    </div>
  </div>    

  <div class="row">
    <div class="col-md-3">
      <b><?= Yii::t('backend', 'Request') ?></b>
    </div>
    <div class="col-md-9">
      <?= $model->demand != '' ? Yii::t('backend', 'Have described') : Yii::t('backend', 'No described')?>
    </div>
  </div>

</div>